# Generated by Django 5.2.1 on 2025-05-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.FileField(upload_to='eeg_data/')),
                ('sampling_rate', models.FloatField(default=250.0)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EEGChannelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('raw_signal', models.TextField()),
                ('highpass', models.TextField()),
                ('lowpass', models.TextField()),
                ('bandpass', models.TextField()),
                ('notch', models.TextField()),
                ('delta_power', models.FloatField()),
                ('theta_power', models.FloatField()),
                ('alpha_power', models.FloatField()),
                ('beta_power', models.FloatField()),
                ('gamma_power', models.FloatField()),
                ('eeg_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.eegdata')),
            ],
            options={
                'ordering': ['channel_name'],
            },
        ),
    ]
