# Generated by Django 4.2.13 on 2025-05-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegdata',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='eegdata',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
