# Generated by Django 4.2.13 on 2025-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_eegdata_age_eegdata_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegchannelanalysis',
            name='spectral_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
