# Generated by Django 4.2.13 on 2025-05-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_eegchannelanalysis_spectral_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eegchannelanalysis',
            old_name='spectral_data',
            new_name='spectrogram_data',
        ),
    ]
